export const appIcons = {
  STATUS: "mingcute:flag-2-line",
  ROLE: "mingcute:briefcase-line",
  COST: "mingcute:wallet-2-line",
  PROGRESS: "mingcute:chart-horizontal-line",
  ADD: "mingcute:add-line",
  APPLY: "mingcute:check-line",
  CLEAR: "mingcute:eraser-line",
  COLORIZE: "mingcute:palette-line",
  TRANSPARENCY: "mingcute:layers-line",
  SELECT: "mingcute:cursor-2-line",
  SCENE: "mingcute:cube-3d-line",
  SHOW: "mingcute:eye-line",
  HIDE: "mingcute:eye-close-line",
  ISOLATE: "mingcute:filter-line",
  FOCUS: "mingcute:target-line",
  REFRESH: "mingcute:refresh-2-line",
  MODELS: "mingcute:cube-line",
  QUERIES: "mingcute:search-2-line",
  VIEWER: "mingcute:monitor-line",
  GRID: "mingcute:grid-line",
  INFORMATION: "mingcute:information-line",
  DOWNLOAD: "mingcute:download-2-line",
  UPLOAD: "mingcute:upload-2-line",
  PROJECTS: "mingcute:building-2-line",
};
